name: Check Albo Pretorio Montecorvino (con Gist, log estesi e notifica errori)

on:
  workflow_dispatch:   # esecuzione manuale
  schedule:
    - cron: '15 * * * *'   # ogni ora al minuto 15

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # 1. Scarica il codice del repository
      - name: Check out repository code
        uses: actions/checkout@v4

      # 2. Imposta l'ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installa le dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Mostra se i secrets sono presenti (debug, non stampa i valori reali)
      - name: Debug secrets presence
        run: |
          echo "TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN != '' }}"
          echo "TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID != '' }}"
          echo "GIST_ID: ${{ secrets.GIST_ID != '' }}"
          echo "GIST_SECRET_TOKEN: ${{ secrets.GIST_SECRET_TOKEN != '' }}"
          echo "GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY != '' }}"

      # 5. Esegue lo script Python con log estesi
      - name: Run Python script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_SECRET_TOKEN: ${{ secrets.GIST_SECRET_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo ">>> Avvio script check_albo_montecorvino_pugliano.py"
          python -u check_albo_montecorvino_pugliano.py
          echo ">>> Script completato"

      # 6. Notifica Telegram in caso di errore di uno step precedente
      - name: Send Telegram notification on failure
        if: failure()
        run: |
          echo "Invio notifica Telegram di errore..."
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="⚠️ Workflow *Check Albo Pretorio Montecorvino* fallito su GitHub Actions.
Job: ${{ github.job }}
Run: ${{ github.run_id }}
Repo: ${{ github.repository }}" \
            -d parse_mode=Markdown
